version: '3.7'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  db:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blog_v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - node
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
